config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include
from django.urls import path
from rest_framework.documentation import include_docs_urls

from vtn.views import HealthCheck

urlpatterns = [
    # OpenADR functionality
    path("", include("vtn.openadr.urls", namespace="openadr")),
    # Administrative user interfaces
    path("", include("vtn.ui.urls", namespace="vtn")),
    path("admin/", admin.site.urls),
    path("admin/django-rq/", include("django_rq.urls")),
    # Management api to create customers, sites etc
    path("api/", include("vtn.api.urls", namespace="api")),
    path("api/docs/", include_docs_urls(title="VTN Management API")),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    # django-x509 CRL URLs
    # These are annoyingly required for the admin backend, but not anything else.
    # We have our own API endpoints for CRLs now at /api/ca/crl, see vtn#26
    path("", include("django_x509.urls", namespace="x509")),
    path("healthcheck", HealthCheck.as_view(), name="healthcheck"),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

vtn/ui/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.urls import reverse_lazy

from . import forms
from . import views

app_name = "vtn.ui"

urlpatterns = [
    path("", views.Overview.as_view(), name="home"),
    path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="login.html",
            authentication_form=forms.Login,
            redirect_authenticated_user=True,
        ),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "password_change/",
        auth_views.PasswordChangeView.as_view(
            template_name="vtn/change_password.html",
            form_class=forms.PasswordChange,
            success_url=reverse_lazy("vtn:home"),
        ),
        name="change_password",
    ),
    path("customer/add", views.CustomerCreate.as_view(), name="customer_add"),
    path("customer/<slug:pk>", views.CustomerDetail.as_view(), name="customer_detail"),
    path("site/create/<int:pk>", views.SiteCreate.as_view(), name="create_site"),
    path("site/<slug:pk>", views.SiteDetail.as_view(), name="site_detail"),
    path("export", views.Export.as_view(), name="export"),
    path("export/<int:pk>.csv", views.export_csv, name="export_events_csv"),
    path("program/sites", views.get_sites_for_program, name="get_sites_for_program"),
    path("event/create", views.EventCreate.as_view(), name="event"),
    path("event/<int:pk>", views.event_view, name="event_dispatch"),
    path("event/<int:pk>/cancel", views.cancel_event, name="event_cancel"),
    path("event/<int:pk>/view", views.EventDetail.as_view(), name="event_detail"),
    path(
        "event/<int:pk>/view/customer",
        views.get_event_details,
        name="event_get_details",
    ),
    path("event/<int:pk>/update", views.EventUpdate.as_view(), name="event_update"),
]

vtn/ui/views.py
from __future__ import unicode_literals

import csv
from collections import OrderedDict
from datetime import timedelta

import django.views.decorators.http as decorators
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Avg
from django.db.models import Case
from django.db.models import Count
from django.db.models import Min
from django.db.models import Q
from django.db.models import When
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from django.urls import reverse
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView
from django.views.generic.edit import ModelFormMixin
from django.views.generic.edit import UpdateView
from django_filters.views import FilterView

from . import filters
from . import forms
from vtn import models
from vtn import services
from vtn.tasks import update_event_statuses


class CustomerCreate(LoginRequiredMixin, CreateView):
    model = models.Customer
    form_class = forms.Customer
    template_name = "vtn/customer_create.html"
    success_url = reverse_lazy("vtn:home")


class CustomerDetail(LoginRequiredMixin, UpdateView):
    model = models.Customer
    form_class = forms.Customer
    template_name = "vtn/customer_detail.html"

    def get_context_data(self, **kwargs):
        context = super(CustomerDetail, self).get_context_data(**kwargs)
        context["sites"] = self.object.site_set.all()
        return context


class SiteDetail(LoginRequiredMixin, UpdateView):
    model = models.Site
    form_class = forms.Site
    template_name = "vtn/site_detail.html"


class SiteCreate(LoginRequiredMixin, CreateView):
    model = models.Site
    form_class = forms.Site
    template_name = "vtn/site_create.html"

    def get_initial(self):
        customer = models.Customer.objects.get(pk=self.kwargs["pk"])
        return {"customer": customer}

    def get_success_url(self):
        return reverse_lazy("vtn:customer_detail", kwargs={"pk": self.kwargs["pk"]})

    def form_valid(self, form):
        self.object = form.save(commit=False)
        if not self.object.ven_id:
            self.object.ven_id = services.get_new_ven_ID()
        self.object.save()

        return HttpResponseRedirect(
            reverse("vtn:customer_detail", kwargs={"pk": self.object.customer_id})
        )


@login_required
@decorators.require_GET
def cancel_event(request, pk):
    services.cancel_event(pk)
    return HttpResponseRedirect(reverse_lazy("vtn:home"))


@login_required
@decorators.require_GET
def export_csv(request, pk):
    event = get_object_or_404(models.Event, pk=pk)
    sites = models.Site.objects.filter(siteevent__event=event)

    t_data = (
        models.Telemetry.objects.filter(site__in=sites)
        .filter(reported_on__range=(event.start, event.end))
        .order_by("-reported_on")
    )

    response = HttpResponse(content_type="text/csv")
    response["Content-Disposition"] = f'attachment; filename="dr-data-event-{pk}.csv"'

    writer = csv.writer(response)

    writer.writerow(
        [
            "program_id",
            "site_id",
            "customer_id",
            "ven_id",
            "created_on",
            "reported_on",
            "report_specifier_id",
            "values",
        ]
    )
    for datum in t_data:
        writer.writerow(
            [
                event.program,
                datum.site.site_id,
                datum.site.customer.id,
                datum.site.ven_id,
                datum.created_on,
                datum.reported_on,
                datum.report_specifier_id,
                datum.values,
            ]
        )

    return response


class Export(LoginRequiredMixin, FilterView):
    filterset_class = filters.ExportFilter
    template_name = "vtn/export.html"

    # We set a queryset here to ensure annotations are in place before filtering starts
    queryset = (
        models.Event.objects.filter(deleted_at=None)
        .annotate(num_sites=Count("sites"))
        .select_related("program")
        .order_by("-start")
    )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["filter_helper"] = forms.ExportFilterHelper()
        return context


class EventCreate(LoginRequiredMixin, CreateView):
    model = models.Event
    form_class = forms.Event
    template_name = "vtn/event_create.html"

    def get_success_url(self):
        return reverse_lazy("vtn:home")

    def get_initial(self):
        initial = {
            "scheduled_notification_time": timezone.now() + timedelta(minutes=1),
            "start": timezone.now() + timedelta(minutes=5),
            "end": timezone.now() + timedelta(minutes=30),
        }
        return initial

    def form_valid(self, form):
        # Serialize the site list into a list of integer IDs to make the
        # boundary cleaner
        if "sites" in form.cleaned_data:
            sites = [site.id for site in form.cleaned_data.pop("sites")]
        else:
            sites = []

        services.create_event(form.cleaned_data, sites)

        return HttpResponseRedirect(self.get_success_url())


class EventUpdate(LoginRequiredMixin, UpdateView):
    model = models.Event
    form_class = forms.Event
    template_name = "vtn/event_update.html"

    def get_context_data(self, **kwargs):
        context = super(EventUpdate, self).get_context_data(**kwargs)
        return context

    def form_valid(self, form):
        # Serialize the site list into a list of integer IDs to make the
        # boundary cleaner
        if "sites" in form.cleaned_data:
            sites = [site.id for site in form.cleaned_data.pop("sites")]
        else:
            sites = []

        services.update_event(
            event_id=self.object.id,
            data=form.cleaned_data,
            selected_sites=sites,
            reason="Edit made in UI",
        )

        return super(ModelFormMixin, self).form_valid(form)


class Overview(LoginRequiredMixin, TemplateView):
    template_name = "vtn/home.html"

    def get_context_data(self, **kwargs):
        # XXX This should not be called here.
        update_event_statuses()

        context = {}

        context["customers"] = models.Customer.objects.annotate(
            sites=Count("site"),
            online=Count(Case(When(site__online=True, then=1))),
            offline=Count(Case(When(site__online=False, then=1))),
        ).order_by("name")

        # DR Event Table
        context["event_data"] = (
            models.Event.objects.filter(end__gt=timezone.now(), deleted_at=None)
            .annotate(numSites=Count("sites"))
            .select_related("program")
            .order_by("start")
        )

        return context


@login_required
def get_sites_for_program(request):
    program_id = request.GET.get("program", default="")
    if program_id == "":
        return JsonResponse([], safe=False)

    event_id = request.GET.get("event", default=None)
    if event_id == "":
        event_id = None

    program = get_object_or_404(models.Program, pk=program_id)

    if event_id:
        qs = program.sites.order_by("site_name").prefetch_related("siteevent_set")
        site_list = [
            {
                "id": site.id,
                "name": str(site),
                "status": (
                    site.siteevent_set.get(event_id=event_id).status
                    if site.siteevent_set.filter(event_id=event_id).count() > 0
                    else ""
                ),
                "selected": site.siteevent_set.filter(
                    ~Q(status="cancelled"), Q(event__id=event_id)
                ).count()
                > 0,
            }
            for site in qs
        ]

    else:
        site_list = [
            {"id": site.id, "name": str(site), "selected": False}
            for site in program.sites.order_by("site_name")
        ]

    return JsonResponse(site_list, safe=False)


@login_required
def get_event_details(request, pk):
    # This function is called when a customer or site is selected
    # on the DR Event detail screen. It loads the graph data for
    # the specified customer or site.

    customer = request.GET.get("customer", "")
    site_pk = request.GET.get("site", "")
    context = {}
    event = models.Event.objects.get(pk=pk)

    if customer != "":
        if customer == "empty":
            sites = models.Site.objects.filter(siteevent__event=event)
        else:
            customers = models.Customer.objects.all().order_by("pk")
            customer = customers.get(pk=customer)
            sites = models.Site.objects.filter(siteevent__event=event).filter(
                customer=customer
            )
    elif site_pk == "empty":
        sites = models.Site.objects.filter(siteevent__event=event)
    else:
        sites = models.Site.objects.filter(pk=site_pk)

    start = event.start
    end = event.end

    date_slice = "trunc(extract(epoch from created_on) / '{}' ) * {}".format(
        str(settings.GRAPH_TIMECHUNK_SECONDS), str(settings.GRAPH_TIMECHUNK_SECONDS)
    )
    t_data = (
        models.Telemetry.objects.filter(site__in=sites)
        .filter(created_on__range=(start, end))
        .extra(select={"date_slice": date_slice})
        .values("date_slice", "site")
        .annotate(
            avg_baseline_power_kw=Avg("baseline_power_kw"),
            avg_measured_power_kw=Avg("measured_power_kw"),
            time=Min("created_on"),
        )
    )
    if t_data.count() == 0:
        context["no_data_for_sites"] = "True"
        return render(request, "vtn/event_customer_detail.html", context)
    else:

vtn/ui/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %}Home{% endblock %} | DRMS</title>
    <meta charset="utf-8">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'css/base_css.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/tables.css' %}">

    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicons/favicon.png' %}">
</head>

<body>
    {% block page %}

    {% if user.is_authenticated %}
    <nav class="navbar navbar-expand-lg navbar-light mb-3">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <span class="navbar-brand mb-0 h1">DRMS</span>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'vtn:home' %}">Overview</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'vtn:export' %}">Export</a>
                </li>
                <li class="nav-item last">
                    {% if request.user.is_superuser %}
                    <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                    {% endif %}
                </li>
            </ul>

            <span class="nav-item dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Welcome, {{ user.username }}
                </a>

                <div class="dropdown-menu">
                    {% if user.has_usable_password %}
                    <a class="dropdown-item" href="{% url 'vtn:change_password' %}">Change password</a></li>
                    {% endif %}
                    <a class="dropdown-item" href="{% url 'vtn:logout' %}">Logoff</a></li>
                    </ul>
            </span>
        </div>
    </nav>
    {% endif %}

    <div class="container-fluid" style="min-height: 90vh">
        <div class="row justify-content-center mb-3">
            <div class="col" style="max-width: 60rem">
                <h2>{% block heading %}{% endblock %}</h2>
            </div>
        </div>

        {% block content %}
        <div class="row justify-content-center">
            <div class="col" style="max-width: 60rem">
                {% block simplecontent %}
                {% endblock simplecontent %}
            </div>
        </div>
        {% endblock content %}
    </div>

    {% endblock page %}

    <footer class="text-center p-4">
        Carbon Co-op OpenADR VTN DRMS Server
    </footer>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>


    {% block scripts %}
    <script>
        $(function() {
            $('[data-toggle="tooltip"]').tooltip()
        })

    </script>
    {% endblock scripts %}

</body>

</html>

vtn/ui/templates/healthcheck.html
up!

vtn/ui/templates/login.html
{% extends "base.html" %}
{% load static crispy_forms_tags %}

{% block page %}

<div class="container-fluid" style="min-height: 90vh">
    <div class="row justify-content-center">
        <div class="col text-center m-5">
            <img
                alt="Carbon Co-op"
                src="{% static 'images/cc-logo-40h.png' %}"
                srcset="{% static 'images/cc-logo-80h.png' %} 2x"
                height="40"
            >
            <h2 class="mb-4">OpenADR server</h2>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col border rounded p-4 mb-5 bg-light" style="max-width: 30rem">
            <h3>Login</h3>

            {% crispy form %}
        </div>
    </div>
</div>

{% endblock page %}