config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include
from django.urls import path
from rest_framework.documentation import include_docs_urls

from vtn.views import HealthCheck

urlpatterns = [
    # OpenADR functionality
    path("", include("vtn.openadr.urls", namespace="openadr")),
    # Administrative user interfaces
    path("", include("vtn.ui.urls", namespace="vtn")),
    path("admin/", admin.site.urls),
    path("admin/django-rq/", include("django_rq.urls")),
    # Management api to create customers, sites etc
    path("api/", include("vtn.api.urls", namespace="api")),
    path("api/docs/", include_docs_urls(title="VTN Management API")),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    # django-x509 CRL URLs
    # These are annoyingly required for the admin backend, but not anything else.
    # We have our own API endpoints for CRLs now at /api/ca/crl, see vtn#26
    path("", include("django_x509.urls", namespace="x509")),
    path("healthcheck", HealthCheck.as_view(), name="healthcheck"),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

vtn/api/urls.py
from django.urls import include
from django.urls import path
from django.views.generic import TemplateView
from rest_framework import routers
from rest_framework.schemas import get_schema_view

from . import views

app_name = "vtn.api"


router = routers.DefaultRouter()
router.register(r"sites", views.SiteViewSet)
router.register(r"customers", views.CustomerViewSet)
router.register(r"programs", views.ProgramViewSet)
router.register(r"events", views.EventViewSet)

schema_url_patterns = [
    path("api/", include("vtn.api.urls")),
]

urlpatterns = [
    path("v1/", include(router.urls)),
    path("v1/events/", views.EventList.as_view()),
    # path("v1/events/<int:event_pk>/", views.Event.as_view()),
    path(
        "v1/sites/<int:pk>/generate_cert/",
        views.GenerateSiteCertificate.as_view(),
        name="site-generate-cert",
    ),
    path("v1/sites/<int:site_pk>/events/", views.SiteEvents.as_view()),
    path(
        "v1/sites/<int:site_pk>/events/<int:event_id>/opt_out",
        views.OptOut.as_view(),
        name="site-event-opt-out",
    ),
    path(
        "v1/sites/<int:site_pk>/events/<int:event_id>/opt_back_in",
        views.OptBackIn.as_view(),
        name="site-event-opt-back-in",
    ),
    path("ca/certificate", views.ca_certificate, name="ca-certificate"),
    path("ca/crl", views.ca_crl, name="ca-crl"),
    path(
        "openapi",
        get_schema_view(
            title="PyOADR-VTN",
            description="Management API",
            patterns=schema_url_patterns,
        ),
        name="openapi-schema",
    ),
    path(
        "docs/",
        TemplateView.as_view(
            template_name="docs.html",
            extra_context={"schema_url": "api:openapi-schema"},
        ),
        name="api-docs",
    ),
]

vtn/openadr/urls.py
from django.urls import path

from . import views


app_name = "vtn.openadr"

urlpatterns = [
    path("OpenADR2/Simple/2.0b/OadrPoll", views.OADRPoll.as_view(), name="oadr-poll"),
    path("OpenADR2/Simple/2.0b/EiEvent", views.EIEvent.as_view(), name="ei-event"),
    path("OpenADR2/Simple/2.0b/EiReport", views.EIReport.as_view(), name="ei-report"),
    # path(
    #     'OpenADR2/Simple/2.0b/EiRegisterParty',
    #     views.EIRegisterParty.as_view(),
    #     name='register-party'
    # ),
]

vtn/ui/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.urls import reverse_lazy

from . import forms
from . import views

app_name = "vtn.ui"

urlpatterns = [
    path("", views.Overview.as_view(), name="home"),
    path(
        "login/",
        auth_views.LoginView.as_view(
            template_name="login.html",
            authentication_form=forms.Login,
            redirect_authenticated_user=True,
        ),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "password_change/",
        auth_views.PasswordChangeView.as_view(
            template_name="vtn/change_password.html",
            form_class=forms.PasswordChange,
            success_url=reverse_lazy("vtn:home"),
        ),
        name="change_password",
    ),
    path("customer/add", views.CustomerCreate.as_view(), name="customer_add"),
    path("customer/<slug:pk>", views.CustomerDetail.as_view(), name="customer_detail"),
    path("site/create/<int:pk>", views.SiteCreate.as_view(), name="create_site"),
    path("site/<slug:pk>", views.SiteDetail.as_view(), name="site_detail"),
    path("export", views.Export.as_view(), name="export"),
    path("export/<int:pk>.csv", views.export_csv, name="export_events_csv"),
    path("program/sites", views.get_sites_for_program, name="get_sites_for_program"),
    path("event/create", views.EventCreate.as_view(), name="event"),
    path("event/<int:pk>", views.event_view, name="event_dispatch"),
    path("event/<int:pk>/cancel", views.cancel_event, name="event_cancel"),
    path("event/<int:pk>/view", views.EventDetail.as_view(), name="event_detail"),
    path(
        "event/<int:pk>/view/customer",
        views.get_event_details,
        name="event_get_details",
    ),
    path("event/<int:pk>/update", views.EventUpdate.as_view(), name="event_update"),
]

vtn/models.py
from __future__ import unicode_literals

import uuid as uuid_lib

from django.contrib.postgres.fields import JSONField
from django.core.validators import MaxValueValidator
from django.core.validators import MinValueValidator
from django.db import models
from django.urls import reverse_lazy
from django_x509.models import Cert

MAX_LENGTH_TEXT = 100
MAX_LENGTH_PHONE = 20
MAX_LENGTH_POSTCODE = 10


class Customer(models.Model):
    """
    An OpenADR Customer.
    A customer can own many sites.

    :param name: Name of the customer
    :param external_id: An external reference ID used when integrating with other systems
    :param utility_id: Unknown. Not currently used by Carbon Coop
    :param contact_name: Contact name
    :param phone_number: Contact phone number
    :param email_address: Contact email address
    """

    name = models.CharField("Name", db_index=True, max_length=MAX_LENGTH_TEXT)
    external_id = models.CharField(
        db_index=True, max_length=MAX_LENGTH_TEXT, blank=True
    )
    utility_id = models.CharField("Utility ID", max_length=MAX_LENGTH_TEXT, blank=True)
    contact_name = models.CharField(
        "Contact Name", max_length=MAX_LENGTH_TEXT, blank=True
    )
    phone_number = models.CharField(
        "Phone Number", max_length=MAX_LENGTH_PHONE, blank=True
    )
    email_address = models.EmailField(blank=True, null=True)

    def get_absolute_url(self):
        return reverse_lazy("vtn:customer_detail", kwargs={"pk": self.pk})

    def __str__(self):
        return self.name

    def sites(self):
        return self.site_set.all()


class Program(models.Model):
    class Meta:
        verbose_name_plural = "Programs"
        verbose_name = "Program"

    name = models.CharField("Program Name", max_length=MAX_LENGTH_TEXT, unique=True)
    sites = models.ManyToManyField("Site", blank=True)
    notes = models.TextField(blank=True)

    def __str__(self):
        return self.name


class Site(models.Model):
    """An OpenADR site.

    :param site_id: A unique identifier. Not currently the primary key, but maybe it could be
    :param customer: The customer the site belongs to
    :param ven_id: The Virtual End Node (VEN) unique ID. There is currently no seperate VEN model.
    :param site_name: A name for the site
    :param external_id: Not currently used at Carbon Coop
    :param site_location_code: Not currently used at Carbon Coop
    :param ven_name: Used if a ven registers itself - not used in Carbon Coop implementation
    :param ip_address: Not currently used at Carbon Coop
    :param site_address1: Address
    :param site_address2: Address
    :param city: City
    :param state: State
    :param post_code: Post code of the site location
    :param contact_name: Contact name - could be different than the customer who owns it
    :param phone_number: Phone number for the `contact_name`
    :param online: If the VEN has recently polled, it is online
    :param last_status_time: The time the VEN last contacted the VTN
    """

    site_id = models.UUIDField(db_index=True, default=uuid_lib.uuid4, editable=False)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, null=False)
    ven_id = models.CharField("VEN ID", max_length=MAX_LENGTH_TEXT, unique=True)

    site_name = models.CharField("Site Name", max_length=MAX_LENGTH_TEXT, blank=True)
    external_id = models.CharField(
        "External ID", max_length=MAX_LENGTH_TEXT, blank=True
    )
    site_location_code = models.CharField(
        "Site Location Code", max_length=MAX_LENGTH_TEXT, blank=True
    )
    ven_name = models.CharField("VEN Name", max_length=MAX_LENGTH_TEXT, blank=True)

    ip_address = models.CharField("IP address", max_length=MAX_LENGTH_TEXT, blank=True)

    site_address1 = models.CharField(
        "Address Line 1", max_length=MAX_LENGTH_TEXT, blank=True
    )
    site_address2 = models.CharField(
        "Address Line 2", max_length=MAX_LENGTH_TEXT, blank=True
    )
    city = models.CharField(verbose_name="City", max_length=MAX_LENGTH_TEXT, blank=True)
    state = models.CharField(
        verbose_name="Region/Province", max_length=MAX_LENGTH_TEXT, blank=True
    )
    post_code = models.CharField(
        "Post Code", max_length=MAX_LENGTH_POSTCODE, blank=True
    )

    contact_name = models.CharField(
        "Contact Name", max_length=MAX_LENGTH_TEXT, blank=True
    )
    phone_number = models.CharField(
        "Phone Number", max_length=MAX_LENGTH_PHONE, blank=True
    )

    online = models.BooleanField(default=False)
    last_status_time = models.DateTimeField("Last Status Time", blank=True, null=True)

    def get_absolute_url(self):
        return reverse_lazy("vtn:customer_detail", kwargs={"pk": self.customer.pk})

    def get_name_display(self):
        if self.site_name == "":
            if self.customer:
                return f"{self.customer.name}'s site"
            else:
                return "unnamed site"
        else:
            return self.site_name

    def __str__(self):
        return "({}) {}".format(self.customer.name, self.site_name)


class AbstractEvent(models.Model):
    class Meta:
        verbose_name_plural = "Events"
        verbose_name = "Event"
        abstract = True

    EVENT_SCHEDULED = "scheduled"
    EVENT_FAR = "far"
    EVENT_NEAR = "near"
    EVENT_ACTIVE = "active"
    EVENT_COMPLETED = "completed"
    EVENT_CANCELLED = "cancelled"
    EVENT_UNRESPONDED = "unresponded"

    STATUS_CHOICES = (
        (EVENT_SCHEDULED, "scheduled"),
        (EVENT_FAR, "far"),
        (EVENT_NEAR, "near"),
        (EVENT_ACTIVE, "active"),
        (EVENT_COMPLETED, "completed"),
        (EVENT_CANCELLED, "cancelled"),
        (EVENT_UNRESPONDED, "unresponded"),
    )

    program = models.ForeignKey(Program, on_delete=models.SET_NULL, null=True)
    scheduled_notification_time = models.DateTimeField("Scheduled Notification Time")
    start = models.DateTimeField("Event Start")
    end = models.DateTimeField("Event End")
    status = models.CharField(
        "Event Status",
        max_length=MAX_LENGTH_TEXT,
        choices=STATUS_CHOICES,
        default="far",
    )
    created_on = models.DateTimeField("Created", auto_now_add=True)
    modification_reason = models.CharField(max_length=MAX_LENGTH_TEXT, blank=True)

    def get_absolute_url(self):
        return reverse_lazy("vtn:home")


class Event(AbstractEvent):
    # TODO: Upgrade Django>3 in prod so we can use IntegerChoices

    # class SignalPayload(models.IntegerChoices):
    #     NORMAL = 0
    #     MODERATE = 1
    #     HIGH = 2
    #     SPECIAL = 3

    sites = models.ManyToManyField(Site, through="SiteEvent", related_name="Sites1")
    deleted_at = models.DateTimeField("Time deleted", blank=True, null=True)
    signal_payload = models.IntegerField(
        null=True, validators=[MinValueValidator(0), MaxValueValidator(4)]
    )

    def __str__(self):
        try:
            program_name = self.program.name
        except AttributeError:
            program_name = "Deleted program"
        return f"{program_name}: Event starts at {self.start}. Event ends at {self.end}"

    @property
    def modification_number(self):
        """Calculated field returning modification number per the OADR spec

        As this is zero-based counting (OADR rule 4) it simply returns the
        number of SupersededEvents
        """
        return self.supersededevent_set.count()


class SupersededEvent(AbstractEvent):
    class Meta:
        verbose_name_plural = "Superseded events"
        verbose_name = "Superseded event"

    event = models.ForeignKey(Event, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        try:
            program_name = self.program.name
        except AttributeError:
            program_name = "Deleted program"
        return (
            f"{program_name}: Superseded version of event {self.event_id} "
            f"starts at {self.start}. Event ends at {self.end}"
        )


class SiteEvent(models.Model):
    class Meta:
        verbose_name_plural = "Site Events"

    EVENT_SCHEDULED = "scheduled"
    EVENT_FAR = "far"
    EVENT_NEAR = "near"
    EVENT_ACTIVE = "active"
    EVENT_COMPLETED = "completed"
    EVENT_CANCELLED = "cancelled"
    EVENT_UNRESPONDED = "unresponded"

    STATUS_CHOICES = (
        (EVENT_SCHEDULED, "scheduled"),
        (EVENT_FAR, "far"),
        (EVENT_NEAR, "near"),
        (EVENT_ACTIVE, "active"),
        (EVENT_COMPLETED, "completed"),
        (EVENT_CANCELLED, "cancelled"),
        (EVENT_UNRESPONDED, "unresponded"),
    )

    OPT_IN = "optIn"
    OPT_OUT = "optOut"
    OPT_NEITHER = "none"

    OPT_IN_CHOICES = ((OPT_IN, "optIn"), (OPT_OUT, "optOut"), (OPT_NEITHER, "Neither"))

    VEN_STATUS_NOT_TOLD = "not_told"
    VEN_STATUS_TOLD = "told"
    VEN_STATUS_ACK = "acknowledged"

    VEN_STATUS_CHOICES = (
        (VEN_STATUS_NOT_TOLD, "not_told"),
        (VEN_STATUS_TOLD, "told"),
        (VEN_STATUS_ACK, "acknowledged"),
    )

    site = models.ForeignKey(Site, models.SET_NULL, null=True)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, null=True)

    status = models.CharField(
        max_length=MAX_LENGTH_TEXT, choices=STATUS_CHOICES, default="scheduled"
    )
    notification_sent_time = models.DateTimeField(
        "Notification Sent Time", blank=True, null=True
    )
    last_status_time = models.DateTimeField("Last Status Time")
    modification_number = models.IntegerField("Modification Number", default=0)
    opt_in = models.CharField(
        max_length=MAX_LENGTH_TEXT, choices=OPT_IN_CHOICES, default="none"
    )
    ven_status = models.CharField(
        max_length=MAX_LENGTH_TEXT, choices=VEN_STATUS_CHOICES, default="not_told"
    )
    last_opt_in = models.DateTimeField("Last opt-in", blank=True, null=True)
    previous_version = models.ForeignKey("self", models.SET_NULL, blank=True, null=True)
    deleted = models.BooleanField(default=False)


class Telemetry(models.Model):

vtn/views.py
from django.views.generic import TemplateView


class HealthCheck(TemplateView):
    template_name = "healthcheck.html"

vtn/ui/templates/vtn/change_password.html
{% extends "base.html" %}

{% load static %}
{% load crispy_forms_tags %}

{% block heading %}
    Change Password
{% endblock heading %}

{% block title %}
    Change password
{% endblock title %}

{% block simplecontent %}
    {% crispy form %}
{% endblock %}

vtn/ui/templates/vtn/customer_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Add customer
{% endblock %}

{% block heading %}
    Add Customer
{% endblock heading %}

{% block simplecontent %}
    {% crispy form %}
{% endblock %}

vtn/ui/templates/vtn/event_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
Add DR Event
{% endblock %}

{% block heading %}
Add DR Event
{% endblock heading %}

{% block simplecontent %}
<div class="alert alert-warning">All times in UTC! Be careful if it's summertime.</div>
{% crispy form %}
{% endblock simplecontent %}

{% block scripts %}
<script>
    $('#id_program').on('change', evt => {
        program_id = $('#id_program').val()

        $.ajax({
            type: "GET",
            url: "{% url 'vtn:get_sites_for_program' %}",
            data: { 'program': program_id }
        })
            .done(function(response) {
                new_options = response.map(
                    option => `<option value='${option.id}'>${option.name}</option>`
                ).join("")

                document.getElementById('id_sites_from').innerHTML = new_options
            })
    })

    $('#id_program').change()
</script>
{% endblock %}

vtn/ui/templates/vtn/event_detail.html
{% extends 'base.html' %}

{% load static %}
{% load timetags %}

{% block title %}
    Event Detail | {{ event.program }}
{% endblock %}

{% block heading %}
    '{{ event.program }}' event detail
{% endblock %}

{% block simplecontent %}
<link href="/static/graph/nv.d3.css" rel="stylesheet" type="text/css">
<link rel="stylesheet" type="text/css" href="{% static 'css/event_detail.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/event_detail.css' %}">

<div class="d-flex w-100 justify-content-between mb-3">
    <div>
        <p>Status: {{ event.status | capfirst }}</p>
        <button type="button" id="cancel_event" class="btn btn-lg btn-danger mb-4" data-toggle="modal"data-target="#cancelModal">Cancel Event</button>
    </div>

    <div>
        <table class="mb-2">
            <tr>
                <th>Notification</th>
                <td>{{ event.scheduled_notification_time }}</td>
            </tr>
            <tr>
                <th>Start</th>
                <td>{{ event.start }}</td>
            </tr>
            <tr>
                <th>End</th>
                <td>{{ event.end }}</td>
            </tr>
        </table>
    </div>
</div>

<nav class="nav nav-tabs nav-stacked" id="myTab" role="tablist">
    <a class="nav-item nav-link active" id="nav-graph-tab" data-toggle="tab" href="#nav-graph" role="tab" aria-controls="nav-graph" aria-expanded="true">Graph</a>
    <a class="nav-item nav-link" id="nav-site-details-tab" data-toggle="tab" href="#nav-site-details" role="tab" aria-controls="nav-site-details">Site Details</a>
</nav>

{% if no_data %}
<div class="tab-pane fade show active" id="nav-graph" role="tabpanel" aria-labelledby="nav-graph-tab">
    <h2 class="text-center">No data for event</h2>
</div>
{% else %}
<div class="tab-content" id="nav-tabContent">
    <div class="tab-pane fade show active" id="nav-graph" role="tabpanel" aria-labelledby="nav-graph-tab">
        <div class="row justify-content-center">
            <div class="col-md-2">
                <h3>Customer</h3>
                {{ customerForm.customer }}
            </div>
            <div class="col-md-2">
                <h3>Site</h3>
                {{ siteForm.site }}
            </div>
        </div>

        <br>
        <br>

        <div id="chart" class="border with-3d-shadow with-transitions" style="width: 1200px">
            <svg style="height:450px; width:1200px; background-color: white"></svg>
        </div>
    </div>
{% endif %}

<div class="tab-pane fade" id="nav-site-details" role="tabpanel" aria-labelledby="nav-site-details-tab">
    <table id="siteTable" class="table table-bordered table-striped table-hovertable-condensed">
        <thead>
        <tr>
            <th>Site</th>
            <th>Notification Sent Time</th>
            <th>Opt-in</th>
            <th>Last opt-in</th>
            <th>Most recent power (kW)</th>
        </tr>
        </thead>
        <tbody>
        {% for site_event in site_events %}
            <tr>
            <td>{{ site_event.site }}</td>
            <td>{{ site_event.notification_sent_time}}</td>

            {% if site_event.opt_in == 'optIn' %}
                <td class="bg-success">Opted in</td>
            {% elif site_event.opt_in == 'optOut' %}
                <td class="bg-danger">Opted out</td>
            {% else %}
                <td>{{ site_event.opt_in | capfirst }}</td>
            {% endif %}

            <td>{{ site_event.last_opt_in }}</td>
            {% if site_event.last_stat > 0 %}
                <td class="negative"> -{{ site_event.last_stat }}</td>
            {% elif site_event.last_stat < 0 %}
                <td class="positive"> +{{ site_event.last_stat }}</td>
                {% else %}
                <td> {{ site_event.last_stat }}</td>
            {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

<div id="cancelModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLiveLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLiveLabel">Confirm</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" style="font-size: 14px">
                <center>
                    <p>Are you sure you want to cancel this event?<br>
                    It is already in progress.</p>
                </center>
            </div>
            <div class="modal-footer" style="text-align: center">
                <button type="button" style="margin: 0 auto" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <a style="margin: 0 auto" href="{% url 'vtn:event_cancel' pk %}" class="btn btn-danger">Cancel</a>
            </div>
        </div>
    </div>
</div>
{% endblock simplecontent %}

{% block scripts %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"
        integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb"
        crossorigin="anonymous"></script>
<script src="/static/graph/d3.min.js"></script>
<script src="/static/graph/nv.d3.js"></script>
<script src="{% static 'js/jquery.floatThead.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.19.1/moment.js"></script>
<script data-require="moment-timezone-with-data@0.4.0" data-semver="0.4.0"
        src="http://momentjs.com/downloads/moment-timezone-with-data.js"></script>

<script>
    $(document).on('change', '#id_customer', function() {
        console.log("change");

        if ($('#id_customer').val() == '') {
            $.ajax({
                type: "GET",
                url: "{% url 'vtn:event_get_details' pk %}",
                data: {'customer': 'empty'}
            })
            .done(function(response) {
                $('#chart').html(response);
                $('#id_site').val('');
            });
        } else {
            $.ajax({
                type: "GET",
                url: "{% url 'vtn:event_get_details' pk %}",
                data: {'customer': $('#id_customer').val()}
            })
            .done(function(response) {
                $('#chart').html(response);
                $('#id_site').val('');
            });
        }
    });

    $(document).on('change', '#id_site', function() {
        console.log($('#id_site').val());

        if ($('#id_site').val() == '') {
            $.ajax({
                type: "GET",
                url: "{% url 'vtn:event_get_details' pk %}",
                data: {'site': 'empty'}
            })
            .done(function(response) {
                $('#chart').html(response);
                $('#id_customer').val('');
            });
        }
        else {
            $.ajax({
                type: "GET",
                url: "{% url 'vtn:event_get_details' pk %}",
                data: {'site': $('#id_site').val()}
            })
            .done(function(response) {
                $('#chart').html(response);
                $('#id_customer').val('');
            });
        }
    });

    data_lineWithFocusChart = [
        {color:'red', key: 'Baseline Power (kw)',
        values: [
            {% for key, value in sum_baseline.items %}
            {x: {{key | toUnixSlice }}, y: {{ value }}},
            {% endfor %}

        ]},
        {color:'blue', key: 'Measured Power (kw)',
        values: [
            {% for key, value in sum_measured.items %}
            {x: ({{key | toUnixSlice }}), y: {{ value }}},
            {% endfor %}
        ]}
    ];

    nv.addGraph(function() {
        var chart = nv.models.lineWithFocusChart();

        chart.margin({left: 100, bottom: 50, right: 100});
        chart.brushExtent([{{ start_focus|toUnix|default:"0"}}, {{ end_focus|toUnix|default:"0" }} ]);

        chart.xAxis
            .axisLabel('Time')
            .tickFormat(function (d) {
                if (d != undefined) {
                    var offset = -1 * moment().zone();
                    return d3.time.format('%-I:%M %p')(moment(d).add(offset, 'm').toDate())

                }
            });

        chart.focusHeight(70 + 20);

        chart.focusMargin({ "bottom": 20 + 20 });

        chart.noData("There is no data to display");

        chart.x2Axis
            .tickFormat(function (d) {
                  var offset = -1 * moment().zone();
                  return d3.time.format('%-I:%M %p')(moment(d).add(offset, 'm').toDate())

            });

        chart.yAxis
            .axisLabel('Power(kW)')
            .tickFormat(d3.format(',.2f'));
        chart.y2Axis.tickFormat(d3.format(',.2f'));
        chart.useInteractiveGuideline(false);

        d3.select('#chart svg')
            .datum(data_lineWithFocusChart)
            .call(chart);

        nv.utils.windowResize(chart.update);

        return chart;
    });

    var $table = $('#siteTable');
    $table.floatThead({
        scrollContainer: function($table){
            return $table.closest('.tableInDiv');
        }
    });
</script>

{% endblock scripts %}

vtn/ui/templates/vtn/event_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    Edit DR Event
{% endblock %}

{% block heading %}
    Edit DR Event
{% endblock heading %}

{% block simplecontent %}
    {% crispy form %}

    <button type="submit" id="cancel_event" class="btn btn-lg btn-danger d-block mx-auto" data-toggle="modal" data-target="#cancelModal">Cancel Event</button>

    <!-- Modal -->
    <div id="cancelModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="exampleModalLiveLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLiveLabel">Confirm</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            </button>
          </div>
          <div class="modal-body" style="font-size: 14px">
            <p>Are you sure you want to cancel this event?</p>
          </div>
          <div class="modal-footer" style="text-align: left">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">
                Don't Cancel
            </button>
            <a href="{% url 'vtn:event_cancel' event.id %}" class="btn btn-danger">
                Cancel Event
            </a>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

{% block scripts %}
<script>
    $('#id_program').on('change', evt => {
        program_id = $('#id_program').val()
        event_id = {{ event.id }}

        $.ajax({
            type: "GET",
            url: "{% url 'vtn:get_sites_for_program' %}",
            data: {'program': program_id, 'event': event_id }
        })
        .done(function(response) {
            selected = row => row.selected ? " selected='selected'" : ""
            new_options = response.map(
                option => `<option value='${option.id}'${selected(option)}>${option.status=='cancelled' ? '<abbr title="cancelled">❌</abbr> ' : ''}${option.name}</option>`
            ).join("")

            document.getElementById('id_sites_from').innerHTML = new_options
        })
    })

    $('#id_program').change()
</script>
{% endblock %}